name: loggycian_networking
description: pure dart network logger
version: 0.1.0+3
repository: https://github.com/rohanjsh/loggycian_networking.git

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  gql: ^1.0.0+1
  graphql: ^5.1.3
  http: ^1.2.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
